apiVersion: v1
kind: ServiceAccount
metadata:
  name: agenttrace-policy-server-sa
  namespace: agenttrace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agenttrace-otel-collector-sa
  namespace: agenttrace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agenttrace-alert-engine-sa
  namespace: agenttrace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agenttrace-dashboard-sa
  namespace: agenttrace
