{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "agenttrace.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
